apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-secret
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: airflow-secret-keys
    creationPolicy: Owner
  data:
    - secretKey: fernet-key
      remoteRef:
        key: prod/airflow/server_keys
        property: fernet_key
    - secretKey: webserver-secret-key
      remoteRef:
        key: prod/airflow/server_keys
        property: webserver_key
    - secretKey: jwt-secret
      remoteRef:
        key: prod/airflow/server_keys
        property: jwt_key

