apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: itineo-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: itineo-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: prod/itineo/app
        property: secret_key
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: prod/itineo/app
        property: jwt_secret_key
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/itineo/db
        property: url
    - secretKey: TRINO_PASSWORD
      remoteRef:
        key: prod/itineo/app
        property: trino_password
    - secretKey: SWAGGER_USER
      remoteRef:
        key: prod/itineo/app
        property: swagger_user
    - secretKey: SWAGGER_PASSWORD
      remoteRef:
        key: prod/itineo/app
        property: swagger_password
