apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-secrets
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: jupyterhub-secrets
    creationPolicy: Owner
  data:
    - secretKey: proxy-token
      remoteRef:
        key: prod/jupyterhub/proxy
        property: token
    - secretKey: auth-password
      remoteRef:
        key: prod/jupyterhub/auth
        property: password
