apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marquez-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: marquez-secret
    creationPolicy: Owner
  data:
    - secretKey: marquez-db-password
      remoteRef:
        key: prod/marquez/db
        property: password
