apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-warehouse-secret
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: minio-warehouse-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: prod/minio/warehouse-credentials
        property: access_key
    - secretKey: secret-key
      remoteRef:
        key: prod/minio/warehouse-credentials
        property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-spark-logs-creds
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: minio-spark-logs-creds
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: prod/minio/spark-logs-credentials
        property: access_key
    - secretKey: secret-key
      remoteRef:
        key: prod/minio/spark-logs-credentials
        property: secret_key
