apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minkms-configuration-secret
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: minkms-configuration
    creationPolicy: Owner
    template:
      data:
        server-config.yaml: |
          version: v1
          hsm:
            hashicorp:
              vault:
                server: http://vault.vault.svc.cluster.local:8200
                transit:
                  key: minkms-sealing-key
                  path: transit/
                approle:
                  path: approle
                  id: "192a7a9b-6476-6fd9-0c88-195207a44824"
                  secret: "{{ .approle_secret_id }}"
  data:
    - secretKey: approle_secret_id
      remoteRef:
        key: prod/minkms/vault-approle
        property: secret_id
