apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-login-secret
  namespace: mlops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: mlflow-auth-admin
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: prod/mlflow/auth-login
        property: user
    - secretKey: password
      remoteRef:
        key: prod/mlflow/auth-login
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-artifacts-s3-keys
  namespace: mlops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: mlflow-artifacts-s3-keys
    creationPolicy: Owner
  data:
    - secretKey: access_key
      remoteRef:
        key: prod/mlflow/artifacts-bucket-s3-keys
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: prod/mlflow/artifacts-bucket-s3-keys
        property: secret_key
