apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nessie-pgcreds
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: nessie-pgcreds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: prod/postgresql-data-platform/nessie-db
        property: user
    - secretKey: password
      remoteRef:
        key: prod/postgresql-data-platform/nessie-db
        property: password
