apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmetadata-mysql-credentials
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: openmetadata-mysql-credentials
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: prod/openmetadata/mysql-credentials
        property: root_password
    - secretKey: mysql-password
      remoteRef:
        key: prod/openmetadata/mysql-credentials
        property: openmetadata_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmetadata-mysql-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: openmetadata-mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-password
      remoteRef:
        key: prod/openmetadata/mysql-credentials
        property: openmetadata_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmetadata-mysql-initdb
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: openmetadata-mysql-initdb
    creationPolicy: Owner
  data:
    - secretKey: init_openmetadata_db_scripts.sql
      remoteRef:
        key: prod/openmetadata/mysql-initdb
        property: init_sql
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmetadata-bot-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: openmetadata-bot
    creationPolicy: Owner
  data:
    - secretKey: jwt-token
      remoteRef:
        key: prod/openmetadata/config_sync_bot
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: itineo-app-db-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: itineo-app-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: prod/postgresql-app/itineo-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: airflow-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: prod/airflow/metadata-db
        property: password
