apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmetadata-bot-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: openmetadata-bot
    creationPolicy: Owner
  data:
    - secretKey: jwt-token
      remoteRef:
        key: prod/openmetadata/config_sync_bot
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: itineo-app-db-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: itineo-app-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: prod/postgresql-app/itineo-db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: airflow-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: prod/airflow/metadata-db
        property: password
