apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmetadata-bot-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: openmetadata-bot
    creationPolicy: Owner
  data:
    - secretKey: jwt-token
      remoteRef:
        key: prod/openmetadata/config_sync_bot
        property: token
