apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-data-platform-credentials
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: postgresql-data-platform-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: prod/postgresql-data-platform/credentials
        property: postgres_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-data-platform-init-scripts
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: postgresql-data-platform-init-scripts
    creationPolicy: Owner
  data:
    - secretKey: init.sql
      remoteRef:
        key: prod/postgresql-data-platform/initdb
        property: init_sql
