apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trino-internal-secret
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: trino-internal-secret
    creationPolicy: Owner
  data:
    - secretKey: shared-secret
      remoteRef:
        key: prod/trino/internal
        property: shared_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trino-password-file
  namespace: data-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: trino-password
    creationPolicy: Owner
  data:
    - secretKey: password.db
      remoteRef:
        key: prod/trino/auth
        property: password_db
