{{- with .Values.minkms.apikey }}
{{- if not .existingSecret }}

{{- if and .key (ne .key "k1:???????????????????????????????????????????") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "%s-apikey" ($.Values.minkms.name | default $.Release.Name)) | quote }}
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace | quote }}
  {{- with $.Values.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $.Values.labels }}
  labels:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  "apikey": {{ .key | quote }}
{{- end }}

{{- end }}
{{- end }}
