{{- with .Values.minkms.hsm }}
{{- if not .existingSecret }}

{{- /* Make sure an HSM is set */}}
{{- if or (not .key) (eq .key "hsm:aes256:????????????????????????????????????????????") }}
{{- $conf := $.Values.minkms.configuration }}
{{- if not (or
      (and $conf $conf.hsm $conf.hsm.minio $conf.hsm.minio.minkms $conf.hsm.minio.minkms.server)
      (and $conf $conf.hsm $conf.hsm.hashicorp $conf.hsm.hashicorp.vault $conf.hsm.hashicorp.vault.server)
) }}
{{- fail "At least one HSM must be defined" }}
{{- end }}

{{- else }}

{{- if hasPrefix "hsm:aes256:" .key }}
{{- if not (eq (len .key) 55) }}
{{- fail "The HSM key has an invalid value" }}
{{- end }}
{{- else if hasPrefix "hsm:chacha20:" .key }}
{{- if not (eq (len .key) 57) }}
{{- fail "The HSM key has an invalid value" }}
{{- end }}
{{- else }}
{{- fail "The administrator identity needs to start with the 'hsm:aes256:' or 'hsm:chacha20:' prefix" }}
{{- end }}

{{- end }}

{{- if and .key (ne .key "hsm:aes256:????????????????????????????????????????????") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "%s-hsm" ($.Values.minkms.name | default $.Release.Name)) | quote }}
  namespace: {{ $.Values.namespaceOverride | default $.Release.Namespace | quote }}
  {{- if $.Values.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $.Values.labels }}
  labels:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
immutable: true
stringData:
  "hsm": {{ .key | quote }}
{{- end }}

{{- end }}
{{- end }}
