apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab-system
  namespace: argocd
spec:
  description: "k8sdatalab project"
  sourceRepos:
    - https://github.com/saidevpro/k8sdatalab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"