apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airflow
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`airflow.k8sdatalab.com`)
      kind: Rule
      services:
        - name: airflow-webserver
          port: 8080
  tls:
    certResolver: letsencrypt
