executor: KubernetesExecutor # ← chaque task = 1 pod k8s

webserverSecretKey: "ca40912fb2205b9fadc2d4174fb90f331bbcde09e0805da8503a2272b305b474"

fernetKeySecretName: airflow-fernet-key

config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: "s3://airflow-logs/logs"
    remote_log_conn_id: "minio_logs"
    encrypt_s3_logs: "False"

images:
  airflow:
    repository: saidsow/airflow
    tag: "3.1.8"
    pullPolicy: Always
  pod_template:
    repository: saidsow/airflow
    tag: "3.1.8"
    pullPolicy: Always

apiServer:
  enabled: true
  args:
    - "bash"
    - "-c"
    - "exec airflow api-server --proxy-headers"

webserver:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

scheduler:
  startupProbe:
    failureThreshold: 30   
    periodSeconds: 30
    timeoutSeconds: 60
    initialDelaySeconds: 30
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

workers: 
  persistence:
    size: 2Gi
  serviceAccount:
    create: false
    name: airflow-worker
  
triggerer:
  persistence:
    size: 5Gi

data:
  metadataConnection:
    user: airflow
    pass: "YJ$fF1&ndM"
    host: postgresql-data-platform.data-platform.svc.cluster.local
    port: 5432
    db: airflow
    protocol: postgresql

postgresql:
  enabled: false

redis:
  enabled: false

logs:
  persistence:
    enabled: false
    size: 2Gi
    storageClassName: longhorn

dags:
  gitSync:
    enabled: true
    repo: https://github.com/saidevpro/k8sdatalab.git
    branch: main
    subPath: src/airflow/dags
    period: 30s
    credentialsSecret: airflow-git-sync-credentials

createUserJob:
  enabled: false
  useHelmHooks: false
  defaultUser:
    role: Admin
    username: said
    email: saidevproject@gmail.com
    firstName: said
    lastName: dev
    password: "Gfz#Klu8n9VC4c7T92D"

migrateDatabaseJob:
  enabled: true
  useHelmHooks: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "false"
  - name: FORWARDED_ALLOW_IPS
    value: "*"
  # - name: AIRFLOW__LOGGING__REMOTE_LOGGING
  #   value: "True"
  # - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
  #   value: "s3://airflow-logs/logs"
  # - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
  #   value: "minio"
  # - name: AIRFLOW__LOGGING__DELETE_LOCAL_LOGS
  #   value: "False"
  # - name: AIRFLOW__LOGGING__ENCRYPT_S3_LOGS
  #   value: "False"

extraPipPackages:
  - apache-airflow-providers-openlineage
  -  "dlt==1.24.0"

extraEnvFrom: |
  - secretRef:
      name: 'dag-bronze-vars'

extraEnv: |-
  - name: AIRFLOW__OPENLINEAGE__NAMESPACE
    value: k8sdatalab
  - name: AIRFLOW__OPENLINEAGE__TRANSPORT
    value: >-
      {"type":"http","url":"http://marquez.observability.svc.cluster.local","endpoint":"api/v1/lineage"}

