# Mode déploiement
executor: KubernetesExecutor # ← chaque task = 1 pod k8s

# Authentification UI
webserverSecretKey: "ca40912fb2205b9fadc2d4174fb90f331bbcde09e0805da8503a2272b305b474"

webserver:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

scheduler:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

# Base de données PostgreSQL
data:
  metadataConnection:
    user: airflow
    pass: "YJ$fF1&ndM"
    host: postgresql-airflow.lab-system.svc.cluster.local
    port: 5432
    db: airflow
    protocol: postgresql

# Désactiver PostgreSQL embarqué
postgresql:
  enabled: false

# Redis pour CeleryExecutor (pas nécessaire avec KubernetesExecutor)
redis:
  enabled: false

# Persistent storage pour les logs
logs:
  persistence:
    enabled: false
    size: 2Gi
    storageClassName: longhorn

# DAGs depuis Git
dags:
  gitSync:
    enabled: true
    repo: https://github.com/saidevpro/k8sdatalab
    branch: main
    subPath: src/airflow/dags/
    period: 60s

# Créer un user admin
createUserJob:
  useHelmHooks: false

defaultAirflowUsername: admin
defaultAirflowPassword: Gfz#Klu8n9VC4c7T92D

# Désactiver les exemples
env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "false"
