executor: KubernetesExecutor # ← chaque task = 1 pod k8s

# Authentification UI
webserverSecretKey: "ca40912fb2205b9fadc2d4174fb90f331bbcde09e0805da8503a2272b305b474"

apiServer:
  enabled: true
  args:
    - "bash"
    - "-c"
    - "exec airflow api-server --proxy-headers"

webserver:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

scheduler:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

# Base de données PostgreSQL
data:
  metadataConnection:
    user: airflow
    pass: "YJ$fF1&ndM"
    host: postgresql-airflow.lab-system.svc.cluster.local
    port: 5432
    db: airflow
    protocol: postgresql

# Désactiver PostgreSQL embarqué
postgresql:
  enabled: false

# Redis pour CeleryExecutor (pas nécessaire avec KubernetesExecutor)
redis:
  enabled: false

# Persistent storage pour les logs
logs:
  persistence:
    enabled: false
    size: 2Gi
    storageClassName: longhorn

# DAGs depuis Git
dags:
  gitSync:
    enabled: true
    repo: https://github.com/saidevpro/k8sdatalab.git
    branch: main
    subPath: src/airflow/dags
    period: 60s
    credentialsSecret: airflow-git-sync-credentials

# Créer un user admin
createUserJob:
  enabled: true
  useHelmHooks: false
  defaultUser:
    role: Admin
    username: said
    email: saidevproject@gmail.com
    firstName: said
    lastName: dev
    password: "Gfz#Klu8n9VC4c7T92D"

migrateDatabaseJob:
  enabled: true
  useHelmHooks: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m

# Désactiver les exemples
env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "false"
  - name: FORWARDED_ALLOW_IPS
    value: "*"

extraPipPackages:
  - apache-airflow-providers-openlineage

extraEnv: |-
  - name: AIRFLOW__OPENLINEAGE__NAMESPACE
    value: k8sdatalab
  - name: AIRFLOW__OPENLINEAGE__TRANSPORT
    value: >-
      {"type":"http","url":"http://marquez.marquez.svc.cluster.local","endpoint":"api/v1/lineage"}
