groupName: acme.k8sdatalab.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

pod:
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
