hub:
  config:
    JupyterHub:
      admin_access: true
      authenticator_class: dummy
    DummyAuthenticator:
      password: "kWw9o06sb4kC"
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - admin
        - dev
        - said
        - abdoulaye

proxy:
  service:
    type: ClusterIP
  secretToken: "442e402846ab4fa51abb464be831920e9cdde19f21db2515cb8600741fdee23f"

singleuser:
  networkPolicy:
    enabled: false
  serviceAccountName: jupyterhub-notebook-sa
  image:
    name: saidsow/jupyterhub-datalab
    tag: "spark-3.5.8"
    pullPolicy: Always

  profileList:
    - display_name: "Data Engineering — Spark 3.5.8"
      description: "PySpark 3.5.8"
      default: true
      kubespawner_override:
        image: saidsow/jupyterhub-datalab:spark-3.5.8
        cpu_limit: 2
        cpu_guarantee: 1
        mem_limit: "4G"
        mem_guarantee: "1G"

    - display_name: "ML, Pytorch - MLflow"
      description: "Pytorch, MLflow, boto3"
      kubespawner_override:
        image: saidsow/jupyterhub-datalab:ml-pytorch-mlflow
        cpu_guarantee: 4
        cpu_limit: 6
        mem_guarantee: "8G"
        mem_limit: "10G"
        environment:
          MLFLOW_TRACKING_URI: "http://mlflow.mlops.svc.cluster.local:5000"
          MLFLOW_S3_ENDPOINT_URL: "http://minio.data-platform.svc.cluster.local:9000"
          AWS_DEFAULT_REGION: "us-east-1"
          TOKENIZERS_PARALLELISM: "false"

  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 1G

  storage:
    type: dynamic
    capacity: 5Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: longhorn
      storageAccessModes: [ReadWriteOnce]

  extraEnv:
    SPARK_HOME: /opt/spark
    MINIO_ENDPOINT: "http://minio.data-platform.svc.cluster.local:9000"
    NESSIE_URI: "http://nessie.data-platform.svc.cluster.local:19120/api/v1"
    TRINO_HOST: "trino.data-platform.svc.cluster.local"
    TRINO_PORT: "8080"
    TRINO_USER: "admin"

  defaultUrl: "/lab"
  startTimeout: 300

scheduling:
  userScheduler:
    enabled: false

  userPlaceholder:
    enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

# Idle culler — close session after 1h
cull:
  enabled: true
  timeout: 3600
  every: 600
