rootUser: "minio"
rootPassword: "+~J3|cr{rQ61"

## minio mode, i.e. standalone or distributed
mode: distributed ## other supported values are "standalone"

# Number of drives attached to a node
drivesPerNode: 1
# Number of MinIO containers running
replicas: 3
# Number of expanded MinIO clusters
pools: 1

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  size: 20Gi
  storageClass: "longhorn"

# environment:
#   MINIO_KMS_SERVER: "https://minkms-minkms.data-platform.svc.cluster.local:7373"
#   MINIO_KMS_ENCLAVE: "minio"
#   MINIO_KMS_SSE_KEY: "minio-default-key"
#   MINIO_KMS_API_KEY: "k1:2muOtixfyiu_HlJfXEc6U636dWqux425zbMPaJldU3U"

resources:
  requests:
    memory: 2Gi
