# rootUser: ""
# rootPassword: ""

existingSecret: "minio-root-login"

## minio mode, i.e. standalone or distributed
mode: distributed ## other supported values are "standalone"

# Number of drives attached to a node
drivesPerNode: 1
# Number of MinIO containers running
replicas: 3
# Number of expanded MinIO clusters
pools: 1

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  size: 20Gi
  storageClass: "longhorn"

environment:
  MINIO_KMS_SERVER: "https://minkms-minkms.data-platform.svc.cluster.local:7373"
  MINIO_KMS_ENCLAVE: "minio"
  MINIO_KMS_SSE_KEY: "minio-vault-key"

extraEnv:
  - name: MINIO_KMS_API_KEY
    valueFrom:
      secretKeyRef:
        name: minio-kms-credentials
        key: api-key

resources:
  requests:
    memory: 2Gi
