minkms:
  configuration:
    existingSecret: false
    hsm:
      hashicorp:
        vault:
          server: http://vault.vault.svc.cluster.local:8200
          transit:
            key: minkms-sealing-key
            path: transit/
          approle:
            path: approle
            id: "<VAULT_APPROLE_ROLE_ID>"
            secret: "<VAULT_APPROLE_SECRET_ID>"
