minkms:
  name: minkms
  image:
    repository: quay.io/minio/aistor/minkms
    tag:  RELEASE.2025-11-12T19-14-51Z
    pullPolicy: IfNotPresent
  configuration:
    existingSecret: false
    hsm:
      hashicorp:
        vault:
          server: http://vault.vault.svc.cluster.local:8200
          transit:
            key: minkms-sealing-key
            path: transit/
          approle:
            path: approle
            id: "868beab0-c0a0-b9c2-caed-40d91e9f52d6"
            secret: "0281cc60-e1d0-bf34-006c-f3f6d246774f"
