replicaCount: 1

image:
  repository: saidsow/mlflow
  tag: 3.7.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgresql-data-platform.data-platform.svc.cluster.local
    port: 5432
    database: mlflow
    user: mlflow
    password: tTmQsWZAQJ6ova6fQk3LVUQmBwtVzxn

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow-artifacts
    path: ""
    existingSecret:
      name: "mlflow-artifacts-s3-keys"
      keyOfAccessKeyId: "accessKey"
      keyOfSecretAccessKey: "secretKey"

auth:
  existingAdminSecret:
    name: "mlflow-auth-admin"
    usernameKey: "user"
    passwordKey: "password"

  postgres:
    enabled: true
    host: postgresql-data-platform.data-platform.svc.cluster.local
    port: 5432
    database: mlflow
    user: mlflow
    password: tTmQsWZAQJ6ova6fQk3LVUQmBwtVzxn

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: "http://minio.data-platform.svc.cluster.local:9000"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_IGNORE_TLS: "true"

extraArgs:
  host: "0.0.0.0"
  port: "5000"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

ingress:
  enabled: false
