replicaCount: 1

image:
  repository: ghcr.io/projectnessie/nessie
  pullPolicy: IfNotPresent

versionStoreType: JDBC2

catalog:
  enabled: true
  iceberg:
    defaultWarehouse: warehouse
    warehouses:
      - name: warehouse
        location: s3://datalake/warehouse
  storage:
    s3:
      defaultOptions:
        endpoint: http://minio.data-platform.svc.cluster.local:9000
        region: us-east-1
        pathStyleAccess: true
        authType: STATIC
        accessKeySecret:
          name: warehouse-s3-credentials
          awsAccessKeyId: AWS_ACCESS_KEY_ID
          awsSecretAccessKey: AWS_SECRET_ACCESS_KEY

jdbc:
  jdbcUrl: jdbc:postgresql://postgresql-data-platform.data-platform.svc.cluster.local:5432/nessie
  secret:
    name: nessie-pgcreds
    username: username
    password: password

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  ports:
    - name: nessie-http
      number: 19120

metrics:
  enabled: false
  tags:
    environment: production

serviceMonitor:
  enabled: false
  interval: "30s"

serviceAccount:
  create: true

log:
  level: INFO
  console:
    enabled: true
    json: false
