openmetadata:
  config:

    elasticsearch:
      host: opensearch-cluster-master.data-platform.svc.cluster.local
      searchType: opensearch
      port: 9200
      scheme: http

    database:
      host: postgresql-data-platform.data-platform.svc.cluster.local
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      databaseName: openmetadata
      auth:
        username: openmetadata
        password:
          secretRef: openmetadata-postgresql-secret
          secretKey: postgres-password
      dbParams: ""

    pipelineServiceClientConfig:
      airflow:
        apiEndpoint: http://airflow-api-server.data-platform.svc.cluster.local:8080
        auth:
          username: openmetadata
          password:
            secretRef: openmetadata-airflow-secret
            secretKey: airflow-password

ingress:
  enabled: false