openmetadata:
  config:
    elasticsearch:
      host: opensearch-cluster-master.data-platform.svc.cluster.local
      searchType: opensearch
      port: 9200
      scheme: http
    database:
      host: openmetadata-mysql.observability.svc.cluster.local
      port: 3306
      driverClass: com.mysql.cj.jdbc.Driver
      dbScheme: mysql
      databaseName: openmetadata_db
      auth:
        username: openmetadata
        password:
          secretRef: openmetadata-mysql-secret
          secretKey: mysql-password
      dbParams: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    pipelineServiceClientConfig:
      enabled: true
      metadataApiEndpoint: http://openmetadata.observability.svc.cluster.local:8585/api
      type: "k8s"
      k8s:
        className: "org.openmetadata.service.clients.pipeline.k8s.K8sPipelineClient"
        ingestionImage: "docker.getcollate.io/openmetadata/ingestion-base:1.12.8"
        imagePullPolicy: "IfNotPresent"
        namespace: "observability"
        serviceAccountName: "openmetadata-ingestion"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        rbac:
          enabled: true
    authentication:
      enableSelfSignup: false
    authorizer:
      initialAdmins:
        - admin
      principalDomain: "k8sdatalab.com"

ingress:
  enabled: false