mysql:
  enabled: true
  fullnameOverride: "openmetadata-mysql"
  auth:
    existingSecret: openmetadata-mysql-credentials
    secretKeys:
      adminPasswordKey: mysql-root-password
  primary:
    persistence:
      storageClass: longhorn
      size: 4Gi
    initdbScriptsSecret: openmetadata-mysql-initdb

opensearch:
  enabled: false
elasticsearch:
  enabled: false
airflow:
  enabled: false
postgresql:
  enabled: false