auth:
  postgresPassword: "cyKoZ1Cf5wONUdVV8FLrjCBuudSfc"
  username: airflow
  password: "YJ$fF1&ndM"
  database: airflow

primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  persistence:
    enabled: true
    size: 5Gi
    storageClass: longhorn
