auth:
  postgresPassword: "cyKoZ1Cf5wONUdVV8FLrjCBuudSfc"

primary:
  extraEnvVars:
    - name: OPENSSL_FIPS
      value: "0"

  initdb:
    scripts:
      init.sql: |
        -- Create users
        CREATE USER airflow WITH PASSWORD 'YJ$fF1&ndM';
        CREATE USER marquez WITH PASSWORD '2j28gK5BL28d';
        CREATE USER nessie WITH PASSWORD 'GZHs5dhB';
        CREATE USER mlflow WITH PASSWORD 'tTmQsWZAQJ6ova6fQk3LVUQmBwtVzxn';
        CREATE USER datahub WITH PASSWORD '4HX6wk2hD3rpNdTRW';
        CREATE USER openmetadata WITH PASSWORD 'LMZnESp7xFQ8vxgz';

        -- Create database
        CREATE DATABASE airflow OWNER airflow;
        CREATE DATABASE marquez OWNER marquez;
        CREATE DATABASE nessie OWNER nessie;
        CREATE DATABASE mlflow OWNER mlflow;
        CREATE DATABASE datahub OWNER datahub;
        CREATE DATABASE openmetadata OWNER openmetadata;

        -- Config priviledge
        GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
        GRANT ALL PRIVILEGES ON DATABASE marquez TO marquez;
        GRANT ALL PRIVILEGES ON DATABASE nessie TO nessie;
        GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflow;
        GRANT ALL PRIVILEGES ON DATABASE datahub TO datahub;
        GRANT ALL PRIVILEGES ON DATABASE openmetadata TO openmetadata;
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  persistence:
    enabled: true
    size: 10Gi
    storageClass: longhorn
