# Grafana
grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn
  ingress:
    enabled: false

# Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 768Mi
        cpu: 500m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  scrapeconfig:
    scrapeInterval: 60s
    evaluationInterval: 60s

# AlertManager
alertmanager:
  enabled: false

# Désactiver les composants inutiles
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
