image:
  repository: saidsow/spark
  pullPolicy: IfNotPresent
  tag: "3.5.8"

serviceAccount:
  create: true
  name: "spark-history-server"

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

spark:
  historyServer:
    cleaner:
      maxAge: 14d
    ui:
      port: 18080
    logDirectory: "s3a://spark-logs/eventlogs/"

s3:
  endpoint: "http://minio.data-platform.svc.cluster.local:9000"
  bucket: "spark-logs"
  existingSecret: minio-spark-logs-creds
  existingSecretAccessKeyKey: access-key
  existingSecretSecretKeyKey: secret-key
