server:
  workers: 2 # ← 1 coordinator + 2 workers

coordinator:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

worker:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

additionalCatalogs:
  iceberg: |-
    connector.name=iceberg
    iceberg.catalog.type=rest
    fs.native-s3.enabled=true
    s3.endpoint=http://minio-api.k8sdatalab.com
    s3.aws-access-key=minio
    s3.aws-secret-key=+~J3|cr{rQ61
    s3.path-style-access=true
    s3.region=us-east-1
    iceberg.warehouse=s3://datalake/warehouse/

service:
  type: ClusterIP
