server:
  workers: 2

coordinator:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  additionalConfigFiles:
    config.properties: |
      http-server.process-forwarded=true

worker:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  additionalConfigFiles:
    config.properties: |
      http-server.process-forwarded=true

service:
  type: ClusterIP
