server:
  workers: 2
  config: 
    authenticationType: "PASSWORD"

additionalConfigProperties:
  - http-server.process-forwarded=true
  - internal-communication.shared-secret=v6PJuMVdoV/gVRKpXCsUeDbYj4dJrzrQC8fVZK/kuA8=
  - http-server.authentication.allow-insecure-over-http=true
  
coordinator:
  additionalConfigProperties:
    - http-server.authentication.type=PASSWORD

  additionalConfigFiles:
    password-authenticator.properties: |
      password-authenticator.name=file
      file.password-file=/etc/trino/passwd/password.db

  additionalVolumes:
    - name: trino-password
      secret:
        secretName: trino-password

  additionalVolumeMounts:
    - name: trino-password
      mountPath: /etc/trino/passwd
      readOnly: true

  resources:
    requests:
      memory: 384Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m


worker:
  resources:
    requests:
      memory: 384Mi
      cpu: 250m
    limits:
      memory: 768Mi
      cpu: 500m

service:
  type: ClusterIP

additionalCatalogs:
  iceberg: |-
    connector.name=iceberg
    iceberg.catalog.type=nessie
    iceberg.nessie-catalog.uri=http://nessie.data-platform.svc.cluster.local:19120/api/v2
    iceberg.nessie-catalog.ref=main
    iceberg.nessie-catalog.default-warehouse-dir=s3://datalake/warehouse

    # MinIO comme stockage S3
    fs.native-s3.enabled=true
    s3.endpoint=http://minio.data-platform.svc.cluster.local:9000
    s3.aws-access-key=UguAWW3vvsLHDLpI4WuY
    s3.aws-secret-key=kDLmVNubBrwGlcjRyCFnSb7ieIJVsdq2b4zsXoT7
    s3.path-style-access=true
    s3.region=us-east-1
