global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true

server:
  enabled: true

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_disable = 1
      }

      storage "file" {
        path = "/vault/data"
      }

  dataStorage:
    enabled: true
    size: 3Gi

  ingress:
    enabled: false

ui:
  enabled: true
