apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: idfm-disruptions-to-iceberg
spec:
  image: saidsow/flink:2.2.0
  flinkVersion: v2_0
  serviceAccount: flink
  mode: native

  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    execution.checkpointing.interval: "60s"
    execution.checkpointing.mode: EXACTLY_ONCE
    state.checkpoints.dir: "s3://datalake/warehouse/flink-checkpoints/disruptions"
    state.savepoints.dir: "s3://datalake/warehouse/flink-savepoints/disruptions"
    s3.endpoint: "http://minio.data-platform.svc.cluster.local:9000"
    s3.path.style.access: "true"
    s3.access-key: "Zpw975O18Eh9kFH3ICBa"
    s3.secret-key: "N9K4zKm30IFLGPN6JoBiCNsiQDKhYABao52N3pjM"

  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5

  taskManager:
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1

  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.idfm.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "idfm-disruptions-raw"
            - name: NESSIE_URI
              value: "http://nessie.data-platform.svc.cluster.local:19120/api/v1"
            - name: NESSIE_REF
              value: "main"
            - name: ICEBERG_WAREHOUSE
              value: "s3://datalake/warehouse/"
            - name: S3_ENDPOINT
              value: "http://minio.data-platform.svc.cluster.local:9000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: warehouse-s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: warehouse-s3-credentials
                  key: AWS_SECRET_ACCESS_KEY

  job:
    jarURI: local:///opt/flink/opt/flink-python-2.2.0.jar
    entryClass: org.apache.flink.client.python.PythonDriver
    args:
      - "-py"
      - "/opt/flink/usrlib/disruptions_raw.py"
    parallelism: 2
    upgradeMode: savepoint
    state: running
