apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: idfm-disruptions-raw
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 604800000
    cleanup.policy: delete
