apiVersion: apps/v1
kind: Deployment
metadata:
  name: idfm-disruptions-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idfm-disruptions-producer
  template:
    metadata:
      labels:
        app: idfm-disruptions-producer
    spec:
      containers:
        - name: producer
          image: saidsow/kafka:0.1.0
          imagePullPolicy: Always
          command: ["python"]
          args: ["producers/disruptions.py"]
          env:
            - name: IDFM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: idfm-api-secret
                  key: IDFM_API_KEY
            - name: IDFM_API_URL
              value: "https://prim.iledefrance-mobilites.fr/marketplace/disruptions_bulk/disruptions/v2"
            - name: POLL_SECONDS
              value: "3600"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.streaming.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "idfm-disruptions-raw"
