{{- if and .Values.s3.enabled (not .Values.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-history-server.fullname" . }}-s3
  labels:
    {{- include "spark-history-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.s3.accessKeyId }}
  {{ .Values.s3.existingSecretAccessKeyKey }}: {{ .Values.s3.accessKeyId | b64enc | quote }}
  {{- else }}
  {{ .Values.s3.existingSecretAccessKeyKey }}: ""
  {{- end }}
  {{- if .Values.s3.secretAccessKey }}
  {{ .Values.s3.existingSecretSecretKeyKey }}: {{ .Values.s3.secretAccessKey | b64enc | quote }}
  {{- else }}
  {{ .Values.s3.existingSecretSecretKeyKey }}: ""
  {{- end }}
{{- end }}
