apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/cert-manager-webhook-ovh
    helm:
      valueFiles:
        - ../../values/cert-manager-webhook-ovh.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
