apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/external-secrets
    helm:
      valueFiles:
        - ../../values/external-secrets-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
