apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marquez
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/marquez
    helm:
      valueFiles:
        - ../../values/marquez-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: marquez
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
