apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: lab-system
spec:
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab.git
    targetRevision: main
    path: argocd/charts/minio
    helm:
      valueFiles:
        - ../values/minio-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
