apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minkms-operator
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/minkms-operator
    helm:
      values: |
        license: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: minkms-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minkms
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/minkms
    helm:
      values: |
        minkms:
          hsm:
            key: "hsm:aes256:VF40XEo1v8uXrtvyIEJjh4wygGkSC4UdSFnvqJH0wG4="
  destination:
    server: https://kubernetes.default.svc
    namespace: minkms
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
