apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minkms-operator
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/minkms-operator
    helm:
      values: |
        license: "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MCwiaWF0IjoxLjc3NDU2MTk1MTQzNjQ1MDMzMWU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiNWQ2ZjA2YjQtYWNiMy00N2RmLTk0MmEtOGNiYzk2ZjRhMGJiIiwib3JnIjoiIiwicGxhbiI6IkZSRUUiLCJzdWIiOiJzYWlkZXZwcm9qZWN0QGdtYWlsLmNvbSIsInRyaWFsIjpmYWxzZX0.7rGZ8E4TQ9h15hucMb7P7HCSnxjpC9tXZhGqFkEgOYCimyO2TcPxGum9k1z5Lmx37q75lpdgJQXihPgqKW88AfKZpoMnCaD8VcOZus-cD8cQ5rp7Qc7u1HWvW7jHUfRA"
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minkms
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/minkms
    helm:
      values: |
        minkms:
          name: minkms
          image:
            repository: quay.io/minio/aistor/minkms
            tag:  RELEASE.2025-11-12T19-14-51Z
            pullPolicy: IfNotPresent
          hsm:
            key: "hsm:aes256:VF40XEo1v8uXrtvyIEJjh4wygGkSC4UdSFnvqJH0wG4="
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
