apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmetadata-governance
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: src/openmetadata
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
