apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/opensearch
    helm:
      valueFiles:
        - ../../values/opensearch-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
