apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-app
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/charts/postgresql
    helm:
      valueFiles:
        - ../../values/postgresql-app-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
