apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-manifests
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/streamings
  destination:
    server: https://kubernetes.default.svc
    namespace: streaming
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
