apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-routes
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/routes
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
