apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets
spec:
  project: lab-system
  source:
    repoURL: https://github.com/saidevpro/k8sdatalab
    targetRevision: main
    path: argocd/vault-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
