apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - k8s/register-job.yaml

configMapGenerator:
  - name: om-register-script
    files:
      - register.py
  - name: om-register-configs
    files:
      - configs/profiler.yaml
      - configs/quality_tests.yaml
      - configs/governance.yaml
